[supervisord]
nodaemon=true

# =========================
# PHP-FPM
# =========================
[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
priority=10

# =========================
# NGINX
# =========================
[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20

# =========================
# LARAVEL QUEUE WORKER
# =========================
[program:laravel-worker]
command=php /var/www/artisan queue:work --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
priority=30